#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAS.DNNDataBase.DataBaseManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="intranetdnn")]
	public partial class DNNLocalizationDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdnn1_Delisoft_TabLocalization(dnn1_Delisoft_TabLocalization instance);
    partial void Updatednn1_Delisoft_TabLocalization(dnn1_Delisoft_TabLocalization instance);
    partial void Deletednn1_Delisoft_TabLocalization(dnn1_Delisoft_TabLocalization instance);
    partial void Insertdnn1_Delisoft_TabLocalization_File(dnn1_Delisoft_TabLocalization_File instance);
    partial void Updatednn1_Delisoft_TabLocalization_File(dnn1_Delisoft_TabLocalization_File instance);
    partial void Deletednn1_Delisoft_TabLocalization_File(dnn1_Delisoft_TabLocalization_File instance);
    partial void Insertdnn1_Delisoft_TabLocalization_Module(dnn1_Delisoft_TabLocalization_Module instance);
    partial void Updatednn1_Delisoft_TabLocalization_Module(dnn1_Delisoft_TabLocalization_Module instance);
    partial void Deletednn1_Delisoft_TabLocalization_Module(dnn1_Delisoft_TabLocalization_Module instance);
    partial void Insertdnn1_Delisoft_TabLocalization_Option(dnn1_Delisoft_TabLocalization_Option instance);
    partial void Updatednn1_Delisoft_TabLocalization_Option(dnn1_Delisoft_TabLocalization_Option instance);
    partial void Deletednn1_Delisoft_TabLocalization_Option(dnn1_Delisoft_TabLocalization_Option instance);
    partial void Insertdnn1_Delisoft_TabLocalization_Portal(dnn1_Delisoft_TabLocalization_Portal instance);
    partial void Updatednn1_Delisoft_TabLocalization_Portal(dnn1_Delisoft_TabLocalization_Portal instance);
    partial void Deletednn1_Delisoft_TabLocalization_Portal(dnn1_Delisoft_TabLocalization_Portal instance);
    partial void Insertdnn1_Delisoft_TabLocalization_Replacement(dnn1_Delisoft_TabLocalization_Replacement instance);
    partial void Updatednn1_Delisoft_TabLocalization_Replacement(dnn1_Delisoft_TabLocalization_Replacement instance);
    partial void Deletednn1_Delisoft_TabLocalization_Replacement(dnn1_Delisoft_TabLocalization_Replacement instance);
    partial void Insertdnn1_Delisoft_TabLocalization_ViewState(dnn1_Delisoft_TabLocalization_ViewState instance);
    partial void Updatednn1_Delisoft_TabLocalization_ViewState(dnn1_Delisoft_TabLocalization_ViewState instance);
    partial void Deletednn1_Delisoft_TabLocalization_ViewState(dnn1_Delisoft_TabLocalization_ViewState instance);
    #endregion
		
		public DNNLocalizationDataClassesDataContext() : 
				base(global::CAS.DNNDataBase.DataBaseManagement.Properties.Settings.Default.intranetdnnConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DNNLocalizationDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DNNLocalizationDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DNNLocalizationDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DNNLocalizationDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dnn1_Delisoft_TabLocalization> dnn1_Delisoft_TabLocalizations
		{
			get
			{
				return this.GetTable<dnn1_Delisoft_TabLocalization>();
			}
		}
		
		public System.Data.Linq.Table<dnn1_Delisoft_TabLocalization_File> dnn1_Delisoft_TabLocalization_Files
		{
			get
			{
				return this.GetTable<dnn1_Delisoft_TabLocalization_File>();
			}
		}
		
		public System.Data.Linq.Table<dnn1_Delisoft_TabLocalization_Module> dnn1_Delisoft_TabLocalization_Modules
		{
			get
			{
				return this.GetTable<dnn1_Delisoft_TabLocalization_Module>();
			}
		}
		
		public System.Data.Linq.Table<dnn1_Delisoft_TabLocalization_Option> dnn1_Delisoft_TabLocalization_Options
		{
			get
			{
				return this.GetTable<dnn1_Delisoft_TabLocalization_Option>();
			}
		}
		
		public System.Data.Linq.Table<dnn1_Delisoft_TabLocalization_Portal> dnn1_Delisoft_TabLocalization_Portals
		{
			get
			{
				return this.GetTable<dnn1_Delisoft_TabLocalization_Portal>();
			}
		}
		
		public System.Data.Linq.Table<dnn1_Delisoft_TabLocalization_Replacement> dnn1_Delisoft_TabLocalization_Replacements
		{
			get
			{
				return this.GetTable<dnn1_Delisoft_TabLocalization_Replacement>();
			}
		}
		
		public System.Data.Linq.Table<dnn1_Delisoft_TabLocalization_ViewState> dnn1_Delisoft_TabLocalization_ViewStates
		{
			get
			{
				return this.GetTable<dnn1_Delisoft_TabLocalization_ViewState>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dnn1_Delisoft_TabLocalization")]
	public partial class dnn1_Delisoft_TabLocalization : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TabId;
		
		private string _LocaleKey;
		
		private string _TabName;
		
		private string _TabTitle;
		
		private string _TabDescription;
		
		private string _RedirectTo;
		
		private System.Nullable<int> _RequireSSL;
		
		private System.Nullable<int> _IsVisible;
		
		private System.Nullable<int> _DisableLink;
		
		private string _KeyWords;
		
		private string _SkinSrc;
		
		private string _ContainerSrc;
		
		private string _Url;
		
		private string _IconFile;
		
		private System.Nullable<int> _SqlViewState;
		
		private System.Nullable<int> _UseWhiteSpaceRemover;
		
		private string _AdminSkinSrc;
		
		private string _AdminContainerSrc;
		
		private string _LogoFile;
		
		private System.Nullable<int> _AdjustSqlSession;
		
		private System.Nullable<int> _AntiSessionExpiration;
		
		private System.Nullable<int> _AntiSessionExpirationTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTabIdChanging(int value);
    partial void OnTabIdChanged();
    partial void OnLocaleKeyChanging(string value);
    partial void OnLocaleKeyChanged();
    partial void OnTabNameChanging(string value);
    partial void OnTabNameChanged();
    partial void OnTabTitleChanging(string value);
    partial void OnTabTitleChanged();
    partial void OnTabDescriptionChanging(string value);
    partial void OnTabDescriptionChanged();
    partial void OnRedirectToChanging(string value);
    partial void OnRedirectToChanged();
    partial void OnRequireSSLChanging(System.Nullable<int> value);
    partial void OnRequireSSLChanged();
    partial void OnIsVisibleChanging(System.Nullable<int> value);
    partial void OnIsVisibleChanged();
    partial void OnDisableLinkChanging(System.Nullable<int> value);
    partial void OnDisableLinkChanged();
    partial void OnKeyWordsChanging(string value);
    partial void OnKeyWordsChanged();
    partial void OnSkinSrcChanging(string value);
    partial void OnSkinSrcChanged();
    partial void OnContainerSrcChanging(string value);
    partial void OnContainerSrcChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnIconFileChanging(string value);
    partial void OnIconFileChanged();
    partial void OnSqlViewStateChanging(System.Nullable<int> value);
    partial void OnSqlViewStateChanged();
    partial void OnUseWhiteSpaceRemoverChanging(System.Nullable<int> value);
    partial void OnUseWhiteSpaceRemoverChanged();
    partial void OnAdminSkinSrcChanging(string value);
    partial void OnAdminSkinSrcChanged();
    partial void OnAdminContainerSrcChanging(string value);
    partial void OnAdminContainerSrcChanged();
    partial void OnLogoFileChanging(string value);
    partial void OnLogoFileChanged();
    partial void OnAdjustSqlSessionChanging(System.Nullable<int> value);
    partial void OnAdjustSqlSessionChanged();
    partial void OnAntiSessionExpirationChanging(System.Nullable<int> value);
    partial void OnAntiSessionExpirationChanged();
    partial void OnAntiSessionExpirationTimeChanging(System.Nullable<int> value);
    partial void OnAntiSessionExpirationTimeChanged();
    #endregion
		
		public dnn1_Delisoft_TabLocalization()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TabId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TabId
		{
			get
			{
				return this._TabId;
			}
			set
			{
				if ((this._TabId != value))
				{
					this.OnTabIdChanging(value);
					this.SendPropertyChanging();
					this._TabId = value;
					this.SendPropertyChanged("TabId");
					this.OnTabIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocaleKey", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LocaleKey
		{
			get
			{
				return this._LocaleKey;
			}
			set
			{
				if ((this._LocaleKey != value))
				{
					this.OnLocaleKeyChanging(value);
					this.SendPropertyChanging();
					this._LocaleKey = value;
					this.SendPropertyChanged("LocaleKey");
					this.OnLocaleKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TabName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TabName
		{
			get
			{
				return this._TabName;
			}
			set
			{
				if ((this._TabName != value))
				{
					this.OnTabNameChanging(value);
					this.SendPropertyChanging();
					this._TabName = value;
					this.SendPropertyChanged("TabName");
					this.OnTabNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TabTitle", DbType="NVarChar(200)")]
		public string TabTitle
		{
			get
			{
				return this._TabTitle;
			}
			set
			{
				if ((this._TabTitle != value))
				{
					this.OnTabTitleChanging(value);
					this.SendPropertyChanging();
					this._TabTitle = value;
					this.SendPropertyChanged("TabTitle");
					this.OnTabTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TabDescription", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string TabDescription
		{
			get
			{
				return this._TabDescription;
			}
			set
			{
				if ((this._TabDescription != value))
				{
					this.OnTabDescriptionChanging(value);
					this.SendPropertyChanging();
					this._TabDescription = value;
					this.SendPropertyChanged("TabDescription");
					this.OnTabDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RedirectTo", DbType="NVarChar(200)")]
		public string RedirectTo
		{
			get
			{
				return this._RedirectTo;
			}
			set
			{
				if ((this._RedirectTo != value))
				{
					this.OnRedirectToChanging(value);
					this.SendPropertyChanging();
					this._RedirectTo = value;
					this.SendPropertyChanged("RedirectTo");
					this.OnRedirectToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequireSSL", DbType="Int")]
		public System.Nullable<int> RequireSSL
		{
			get
			{
				return this._RequireSSL;
			}
			set
			{
				if ((this._RequireSSL != value))
				{
					this.OnRequireSSLChanging(value);
					this.SendPropertyChanging();
					this._RequireSSL = value;
					this.SendPropertyChanged("RequireSSL");
					this.OnRequireSSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVisible", DbType="Int")]
		public System.Nullable<int> IsVisible
		{
			get
			{
				return this._IsVisible;
			}
			set
			{
				if ((this._IsVisible != value))
				{
					this.OnIsVisibleChanging(value);
					this.SendPropertyChanging();
					this._IsVisible = value;
					this.SendPropertyChanged("IsVisible");
					this.OnIsVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisableLink", DbType="Int")]
		public System.Nullable<int> DisableLink
		{
			get
			{
				return this._DisableLink;
			}
			set
			{
				if ((this._DisableLink != value))
				{
					this.OnDisableLinkChanging(value);
					this.SendPropertyChanging();
					this._DisableLink = value;
					this.SendPropertyChanged("DisableLink");
					this.OnDisableLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWords", DbType="NVarChar(500)")]
		public string KeyWords
		{
			get
			{
				return this._KeyWords;
			}
			set
			{
				if ((this._KeyWords != value))
				{
					this.OnKeyWordsChanging(value);
					this.SendPropertyChanging();
					this._KeyWords = value;
					this.SendPropertyChanged("KeyWords");
					this.OnKeyWordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkinSrc", DbType="NVarChar(200)")]
		public string SkinSrc
		{
			get
			{
				return this._SkinSrc;
			}
			set
			{
				if ((this._SkinSrc != value))
				{
					this.OnSkinSrcChanging(value);
					this.SendPropertyChanging();
					this._SkinSrc = value;
					this.SendPropertyChanged("SkinSrc");
					this.OnSkinSrcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContainerSrc", DbType="NVarChar(200)")]
		public string ContainerSrc
		{
			get
			{
				return this._ContainerSrc;
			}
			set
			{
				if ((this._ContainerSrc != value))
				{
					this.OnContainerSrcChanging(value);
					this.SendPropertyChanging();
					this._ContainerSrc = value;
					this.SendPropertyChanged("ContainerSrc");
					this.OnContainerSrcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(255)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconFile", DbType="NVarChar(100)")]
		public string IconFile
		{
			get
			{
				return this._IconFile;
			}
			set
			{
				if ((this._IconFile != value))
				{
					this.OnIconFileChanging(value);
					this.SendPropertyChanging();
					this._IconFile = value;
					this.SendPropertyChanged("IconFile");
					this.OnIconFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SqlViewState", DbType="Int")]
		public System.Nullable<int> SqlViewState
		{
			get
			{
				return this._SqlViewState;
			}
			set
			{
				if ((this._SqlViewState != value))
				{
					this.OnSqlViewStateChanging(value);
					this.SendPropertyChanging();
					this._SqlViewState = value;
					this.SendPropertyChanged("SqlViewState");
					this.OnSqlViewStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseWhiteSpaceRemover", DbType="Int")]
		public System.Nullable<int> UseWhiteSpaceRemover
		{
			get
			{
				return this._UseWhiteSpaceRemover;
			}
			set
			{
				if ((this._UseWhiteSpaceRemover != value))
				{
					this.OnUseWhiteSpaceRemoverChanging(value);
					this.SendPropertyChanging();
					this._UseWhiteSpaceRemover = value;
					this.SendPropertyChanged("UseWhiteSpaceRemover");
					this.OnUseWhiteSpaceRemoverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminSkinSrc", DbType="NVarChar(200)")]
		public string AdminSkinSrc
		{
			get
			{
				return this._AdminSkinSrc;
			}
			set
			{
				if ((this._AdminSkinSrc != value))
				{
					this.OnAdminSkinSrcChanging(value);
					this.SendPropertyChanging();
					this._AdminSkinSrc = value;
					this.SendPropertyChanged("AdminSkinSrc");
					this.OnAdminSkinSrcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminContainerSrc", DbType="NVarChar(200)")]
		public string AdminContainerSrc
		{
			get
			{
				return this._AdminContainerSrc;
			}
			set
			{
				if ((this._AdminContainerSrc != value))
				{
					this.OnAdminContainerSrcChanging(value);
					this.SendPropertyChanging();
					this._AdminContainerSrc = value;
					this.SendPropertyChanged("AdminContainerSrc");
					this.OnAdminContainerSrcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoFile", DbType="NVarChar(100)")]
		public string LogoFile
		{
			get
			{
				return this._LogoFile;
			}
			set
			{
				if ((this._LogoFile != value))
				{
					this.OnLogoFileChanging(value);
					this.SendPropertyChanging();
					this._LogoFile = value;
					this.SendPropertyChanged("LogoFile");
					this.OnLogoFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjustSqlSession", DbType="Int")]
		public System.Nullable<int> AdjustSqlSession
		{
			get
			{
				return this._AdjustSqlSession;
			}
			set
			{
				if ((this._AdjustSqlSession != value))
				{
					this.OnAdjustSqlSessionChanging(value);
					this.SendPropertyChanging();
					this._AdjustSqlSession = value;
					this.SendPropertyChanged("AdjustSqlSession");
					this.OnAdjustSqlSessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AntiSessionExpiration", DbType="Int")]
		public System.Nullable<int> AntiSessionExpiration
		{
			get
			{
				return this._AntiSessionExpiration;
			}
			set
			{
				if ((this._AntiSessionExpiration != value))
				{
					this.OnAntiSessionExpirationChanging(value);
					this.SendPropertyChanging();
					this._AntiSessionExpiration = value;
					this.SendPropertyChanged("AntiSessionExpiration");
					this.OnAntiSessionExpirationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AntiSessionExpirationTime", DbType="Int")]
		public System.Nullable<int> AntiSessionExpirationTime
		{
			get
			{
				return this._AntiSessionExpirationTime;
			}
			set
			{
				if ((this._AntiSessionExpirationTime != value))
				{
					this.OnAntiSessionExpirationTimeChanging(value);
					this.SendPropertyChanging();
					this._AntiSessionExpirationTime = value;
					this.SendPropertyChanged("AntiSessionExpirationTime");
					this.OnAntiSessionExpirationTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dnn1_Delisoft_TabLocalization_Files")]
	public partial class dnn1_Delisoft_TabLocalization_File : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FileId;
		
		private int _PortalId;
		
		private string _FriendlyName;
		
		private int _FileType;
		
		private string _LanguagesIncluded;
		
		private string _TabsIncluded;
		
		private string _FileURL;
		
		private System.Nullable<int> _FileOrder;
		
		private bool _Disabled;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFileIdChanging(int value);
    partial void OnFileIdChanged();
    partial void OnPortalIdChanging(int value);
    partial void OnPortalIdChanged();
    partial void OnFriendlyNameChanging(string value);
    partial void OnFriendlyNameChanged();
    partial void OnFileTypeChanging(int value);
    partial void OnFileTypeChanged();
    partial void OnLanguagesIncludedChanging(string value);
    partial void OnLanguagesIncludedChanged();
    partial void OnTabsIncludedChanging(string value);
    partial void OnTabsIncludedChanged();
    partial void OnFileURLChanging(string value);
    partial void OnFileURLChanged();
    partial void OnFileOrderChanging(System.Nullable<int> value);
    partial void OnFileOrderChanged();
    partial void OnDisabledChanging(bool value);
    partial void OnDisabledChanged();
    #endregion
		
		public dnn1_Delisoft_TabLocalization_File()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FileId
		{
			get
			{
				return this._FileId;
			}
			set
			{
				if ((this._FileId != value))
				{
					this.OnFileIdChanging(value);
					this.SendPropertyChanging();
					this._FileId = value;
					this.SendPropertyChanged("FileId");
					this.OnFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalId", DbType="Int NOT NULL")]
		public int PortalId
		{
			get
			{
				return this._PortalId;
			}
			set
			{
				if ((this._PortalId != value))
				{
					this.OnPortalIdChanging(value);
					this.SendPropertyChanging();
					this._PortalId = value;
					this.SendPropertyChanged("PortalId");
					this.OnPortalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FriendlyName", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string FriendlyName
		{
			get
			{
				return this._FriendlyName;
			}
			set
			{
				if ((this._FriendlyName != value))
				{
					this.OnFriendlyNameChanging(value);
					this.SendPropertyChanging();
					this._FriendlyName = value;
					this.SendPropertyChanged("FriendlyName");
					this.OnFriendlyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileType", DbType="Int NOT NULL")]
		public int FileType
		{
			get
			{
				return this._FileType;
			}
			set
			{
				if ((this._FileType != value))
				{
					this.OnFileTypeChanging(value);
					this.SendPropertyChanging();
					this._FileType = value;
					this.SendPropertyChanged("FileType");
					this.OnFileTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguagesIncluded", DbType="NVarChar(100)")]
		public string LanguagesIncluded
		{
			get
			{
				return this._LanguagesIncluded;
			}
			set
			{
				if ((this._LanguagesIncluded != value))
				{
					this.OnLanguagesIncludedChanging(value);
					this.SendPropertyChanging();
					this._LanguagesIncluded = value;
					this.SendPropertyChanged("LanguagesIncluded");
					this.OnLanguagesIncludedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TabsIncluded", DbType="NVarChar(100)")]
		public string TabsIncluded
		{
			get
			{
				return this._TabsIncluded;
			}
			set
			{
				if ((this._TabsIncluded != value))
				{
					this.OnTabsIncludedChanging(value);
					this.SendPropertyChanging();
					this._TabsIncluded = value;
					this.SendPropertyChanged("TabsIncluded");
					this.OnTabsIncludedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileURL", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string FileURL
		{
			get
			{
				return this._FileURL;
			}
			set
			{
				if ((this._FileURL != value))
				{
					this.OnFileURLChanging(value);
					this.SendPropertyChanging();
					this._FileURL = value;
					this.SendPropertyChanged("FileURL");
					this.OnFileURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileOrder", DbType="Int")]
		public System.Nullable<int> FileOrder
		{
			get
			{
				return this._FileOrder;
			}
			set
			{
				if ((this._FileOrder != value))
				{
					this.OnFileOrderChanging(value);
					this.SendPropertyChanging();
					this._FileOrder = value;
					this.SendPropertyChanged("FileOrder");
					this.OnFileOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disabled", DbType="Bit NOT NULL")]
		public bool Disabled
		{
			get
			{
				return this._Disabled;
			}
			set
			{
				if ((this._Disabled != value))
				{
					this.OnDisabledChanging(value);
					this.SendPropertyChanging();
					this._Disabled = value;
					this.SendPropertyChanged("Disabled");
					this.OnDisabledChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dnn1_Delisoft_TabLocalization_Modules")]
	public partial class dnn1_Delisoft_TabLocalization_Module : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ModuleId;
		
		private string _LocaleKey;
		
		private string _ModuleTitle;
		
		private string _IconFile;
		
		private string _Alignment;
		
		private string _Header;
		
		private string _Footer;
		
		private string _ContainerSrc;
		
		private bool _ModuleHidden;
		
		private string _AdminSkinSrc;
		
		private string _AdminContainerSrc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnModuleIdChanging(int value);
    partial void OnModuleIdChanged();
    partial void OnLocaleKeyChanging(string value);
    partial void OnLocaleKeyChanged();
    partial void OnModuleTitleChanging(string value);
    partial void OnModuleTitleChanged();
    partial void OnIconFileChanging(string value);
    partial void OnIconFileChanged();
    partial void OnAlignmentChanging(string value);
    partial void OnAlignmentChanged();
    partial void OnHeaderChanging(string value);
    partial void OnHeaderChanged();
    partial void OnFooterChanging(string value);
    partial void OnFooterChanged();
    partial void OnContainerSrcChanging(string value);
    partial void OnContainerSrcChanged();
    partial void OnModuleHiddenChanging(bool value);
    partial void OnModuleHiddenChanged();
    partial void OnAdminSkinSrcChanging(string value);
    partial void OnAdminSkinSrcChanged();
    partial void OnAdminContainerSrcChanging(string value);
    partial void OnAdminContainerSrcChanged();
    #endregion
		
		public dnn1_Delisoft_TabLocalization_Module()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ModuleId
		{
			get
			{
				return this._ModuleId;
			}
			set
			{
				if ((this._ModuleId != value))
				{
					this.OnModuleIdChanging(value);
					this.SendPropertyChanging();
					this._ModuleId = value;
					this.SendPropertyChanged("ModuleId");
					this.OnModuleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocaleKey", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LocaleKey
		{
			get
			{
				return this._LocaleKey;
			}
			set
			{
				if ((this._LocaleKey != value))
				{
					this.OnLocaleKeyChanging(value);
					this.SendPropertyChanging();
					this._LocaleKey = value;
					this.SendPropertyChanged("LocaleKey");
					this.OnLocaleKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleTitle", DbType="NVarChar(256)")]
		public string ModuleTitle
		{
			get
			{
				return this._ModuleTitle;
			}
			set
			{
				if ((this._ModuleTitle != value))
				{
					this.OnModuleTitleChanging(value);
					this.SendPropertyChanging();
					this._ModuleTitle = value;
					this.SendPropertyChanged("ModuleTitle");
					this.OnModuleTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconFile", DbType="NVarChar(100)")]
		public string IconFile
		{
			get
			{
				return this._IconFile;
			}
			set
			{
				if ((this._IconFile != value))
				{
					this.OnIconFileChanging(value);
					this.SendPropertyChanging();
					this._IconFile = value;
					this.SendPropertyChanged("IconFile");
					this.OnIconFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alignment", DbType="NVarChar(10)")]
		public string Alignment
		{
			get
			{
				return this._Alignment;
			}
			set
			{
				if ((this._Alignment != value))
				{
					this.OnAlignmentChanging(value);
					this.SendPropertyChanging();
					this._Alignment = value;
					this.SendPropertyChanged("Alignment");
					this.OnAlignmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Header", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Header
		{
			get
			{
				return this._Header;
			}
			set
			{
				if ((this._Header != value))
				{
					this.OnHeaderChanging(value);
					this.SendPropertyChanging();
					this._Header = value;
					this.SendPropertyChanged("Header");
					this.OnHeaderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Footer", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Footer
		{
			get
			{
				return this._Footer;
			}
			set
			{
				if ((this._Footer != value))
				{
					this.OnFooterChanging(value);
					this.SendPropertyChanging();
					this._Footer = value;
					this.SendPropertyChanged("Footer");
					this.OnFooterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContainerSrc", DbType="NVarChar(200)")]
		public string ContainerSrc
		{
			get
			{
				return this._ContainerSrc;
			}
			set
			{
				if ((this._ContainerSrc != value))
				{
					this.OnContainerSrcChanging(value);
					this.SendPropertyChanging();
					this._ContainerSrc = value;
					this.SendPropertyChanged("ContainerSrc");
					this.OnContainerSrcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleHidden", DbType="Bit NOT NULL")]
		public bool ModuleHidden
		{
			get
			{
				return this._ModuleHidden;
			}
			set
			{
				if ((this._ModuleHidden != value))
				{
					this.OnModuleHiddenChanging(value);
					this.SendPropertyChanging();
					this._ModuleHidden = value;
					this.SendPropertyChanged("ModuleHidden");
					this.OnModuleHiddenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminSkinSrc", DbType="NVarChar(200)")]
		public string AdminSkinSrc
		{
			get
			{
				return this._AdminSkinSrc;
			}
			set
			{
				if ((this._AdminSkinSrc != value))
				{
					this.OnAdminSkinSrcChanging(value);
					this.SendPropertyChanging();
					this._AdminSkinSrc = value;
					this.SendPropertyChanged("AdminSkinSrc");
					this.OnAdminSkinSrcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminContainerSrc", DbType="NVarChar(200)")]
		public string AdminContainerSrc
		{
			get
			{
				return this._AdminContainerSrc;
			}
			set
			{
				if ((this._AdminContainerSrc != value))
				{
					this.OnAdminContainerSrcChanging(value);
					this.SendPropertyChanging();
					this._AdminContainerSrc = value;
					this.SendPropertyChanged("AdminContainerSrc");
					this.OnAdminContainerSrcChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dnn1_Delisoft_TabLocalization_Options")]
	public partial class dnn1_Delisoft_TabLocalization_Option : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PortalId;
		
		private int _UseSQLViewState;
		
		private bool _UseTabLocalization;
		
		private bool _UseModuleLocalization;
		
		private bool _EnableSearch;
		
		private string _SQLViewStateIP;
		
		private bool _TabPreviewEnabled;
		
		private bool _UsePortalSettingsLocalization;
		
		private bool _SelectorNotUsingCookie;
		
		private bool _SelectorNotUsingParam;
		
		private bool _SelectorNotUsingBrowser;
		
		private string _SelectorParamText;
		
		private bool _SqlViewStatePerPage;
		
		private bool _SelectorNotUsingGeoIP;
		
		private string _SelectorCookieName;
		
		private string _LocaleDetectionOrder;
		
		private bool _UseWhiteSpaceRemover;
		
		private bool _UseLocaleTranslation;
		
		private string _LocaleTranslationRules;
		
		private bool _SelectorParamAutoreplaceURL;
		
		private bool _SelectorParamAutoreplaceSOLPART;
		
		private string _PortalAliasDefaults;
		
		private string _CustomNames;
		
		private System.Nullable<bool> _AdjustSqlSession;
		
		private System.Nullable<int> _AntiSessionExpiration;
		
		private System.Nullable<int> _AntiSessionExpirationTime;
		
		private bool _ForceParamExistance;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPortalIdChanging(int value);
    partial void OnPortalIdChanged();
    partial void OnUseSQLViewStateChanging(int value);
    partial void OnUseSQLViewStateChanged();
    partial void OnUseTabLocalizationChanging(bool value);
    partial void OnUseTabLocalizationChanged();
    partial void OnUseModuleLocalizationChanging(bool value);
    partial void OnUseModuleLocalizationChanged();
    partial void OnEnableSearchChanging(bool value);
    partial void OnEnableSearchChanged();
    partial void OnSQLViewStateIPChanging(string value);
    partial void OnSQLViewStateIPChanged();
    partial void OnTabPreviewEnabledChanging(bool value);
    partial void OnTabPreviewEnabledChanged();
    partial void OnUsePortalSettingsLocalizationChanging(bool value);
    partial void OnUsePortalSettingsLocalizationChanged();
    partial void OnSelectorNotUsingCookieChanging(bool value);
    partial void OnSelectorNotUsingCookieChanged();
    partial void OnSelectorNotUsingParamChanging(bool value);
    partial void OnSelectorNotUsingParamChanged();
    partial void OnSelectorNotUsingBrowserChanging(bool value);
    partial void OnSelectorNotUsingBrowserChanged();
    partial void OnSelectorParamTextChanging(string value);
    partial void OnSelectorParamTextChanged();
    partial void OnSqlViewStatePerPageChanging(bool value);
    partial void OnSqlViewStatePerPageChanged();
    partial void OnSelectorNotUsingGeoIPChanging(bool value);
    partial void OnSelectorNotUsingGeoIPChanged();
    partial void OnSelectorCookieNameChanging(string value);
    partial void OnSelectorCookieNameChanged();
    partial void OnLocaleDetectionOrderChanging(string value);
    partial void OnLocaleDetectionOrderChanged();
    partial void OnUseWhiteSpaceRemoverChanging(bool value);
    partial void OnUseWhiteSpaceRemoverChanged();
    partial void OnUseLocaleTranslationChanging(bool value);
    partial void OnUseLocaleTranslationChanged();
    partial void OnLocaleTranslationRulesChanging(string value);
    partial void OnLocaleTranslationRulesChanged();
    partial void OnSelectorParamAutoreplaceURLChanging(bool value);
    partial void OnSelectorParamAutoreplaceURLChanged();
    partial void OnSelectorParamAutoreplaceSOLPARTChanging(bool value);
    partial void OnSelectorParamAutoreplaceSOLPARTChanged();
    partial void OnPortalAliasDefaultsChanging(string value);
    partial void OnPortalAliasDefaultsChanged();
    partial void OnCustomNamesChanging(string value);
    partial void OnCustomNamesChanged();
    partial void OnAdjustSqlSessionChanging(System.Nullable<bool> value);
    partial void OnAdjustSqlSessionChanged();
    partial void OnAntiSessionExpirationChanging(System.Nullable<int> value);
    partial void OnAntiSessionExpirationChanged();
    partial void OnAntiSessionExpirationTimeChanging(System.Nullable<int> value);
    partial void OnAntiSessionExpirationTimeChanged();
    partial void OnForceParamExistanceChanging(bool value);
    partial void OnForceParamExistanceChanged();
    #endregion
		
		public dnn1_Delisoft_TabLocalization_Option()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PortalId
		{
			get
			{
				return this._PortalId;
			}
			set
			{
				if ((this._PortalId != value))
				{
					this.OnPortalIdChanging(value);
					this.SendPropertyChanging();
					this._PortalId = value;
					this.SendPropertyChanged("PortalId");
					this.OnPortalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseSQLViewState", DbType="Int NOT NULL")]
		public int UseSQLViewState
		{
			get
			{
				return this._UseSQLViewState;
			}
			set
			{
				if ((this._UseSQLViewState != value))
				{
					this.OnUseSQLViewStateChanging(value);
					this.SendPropertyChanging();
					this._UseSQLViewState = value;
					this.SendPropertyChanged("UseSQLViewState");
					this.OnUseSQLViewStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseTabLocalization", DbType="Bit NOT NULL")]
		public bool UseTabLocalization
		{
			get
			{
				return this._UseTabLocalization;
			}
			set
			{
				if ((this._UseTabLocalization != value))
				{
					this.OnUseTabLocalizationChanging(value);
					this.SendPropertyChanging();
					this._UseTabLocalization = value;
					this.SendPropertyChanged("UseTabLocalization");
					this.OnUseTabLocalizationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseModuleLocalization", DbType="Bit NOT NULL")]
		public bool UseModuleLocalization
		{
			get
			{
				return this._UseModuleLocalization;
			}
			set
			{
				if ((this._UseModuleLocalization != value))
				{
					this.OnUseModuleLocalizationChanging(value);
					this.SendPropertyChanging();
					this._UseModuleLocalization = value;
					this.SendPropertyChanged("UseModuleLocalization");
					this.OnUseModuleLocalizationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableSearch", DbType="Bit NOT NULL")]
		public bool EnableSearch
		{
			get
			{
				return this._EnableSearch;
			}
			set
			{
				if ((this._EnableSearch != value))
				{
					this.OnEnableSearchChanging(value);
					this.SendPropertyChanging();
					this._EnableSearch = value;
					this.SendPropertyChanged("EnableSearch");
					this.OnEnableSearchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQLViewStateIP", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string SQLViewStateIP
		{
			get
			{
				return this._SQLViewStateIP;
			}
			set
			{
				if ((this._SQLViewStateIP != value))
				{
					this.OnSQLViewStateIPChanging(value);
					this.SendPropertyChanging();
					this._SQLViewStateIP = value;
					this.SendPropertyChanged("SQLViewStateIP");
					this.OnSQLViewStateIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TabPreviewEnabled", DbType="Bit NOT NULL")]
		public bool TabPreviewEnabled
		{
			get
			{
				return this._TabPreviewEnabled;
			}
			set
			{
				if ((this._TabPreviewEnabled != value))
				{
					this.OnTabPreviewEnabledChanging(value);
					this.SendPropertyChanging();
					this._TabPreviewEnabled = value;
					this.SendPropertyChanged("TabPreviewEnabled");
					this.OnTabPreviewEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsePortalSettingsLocalization", DbType="Bit NOT NULL")]
		public bool UsePortalSettingsLocalization
		{
			get
			{
				return this._UsePortalSettingsLocalization;
			}
			set
			{
				if ((this._UsePortalSettingsLocalization != value))
				{
					this.OnUsePortalSettingsLocalizationChanging(value);
					this.SendPropertyChanging();
					this._UsePortalSettingsLocalization = value;
					this.SendPropertyChanged("UsePortalSettingsLocalization");
					this.OnUsePortalSettingsLocalizationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelectorNotUsingCookie", DbType="Bit NOT NULL")]
		public bool SelectorNotUsingCookie
		{
			get
			{
				return this._SelectorNotUsingCookie;
			}
			set
			{
				if ((this._SelectorNotUsingCookie != value))
				{
					this.OnSelectorNotUsingCookieChanging(value);
					this.SendPropertyChanging();
					this._SelectorNotUsingCookie = value;
					this.SendPropertyChanged("SelectorNotUsingCookie");
					this.OnSelectorNotUsingCookieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelectorNotUsingParam", DbType="Bit NOT NULL")]
		public bool SelectorNotUsingParam
		{
			get
			{
				return this._SelectorNotUsingParam;
			}
			set
			{
				if ((this._SelectorNotUsingParam != value))
				{
					this.OnSelectorNotUsingParamChanging(value);
					this.SendPropertyChanging();
					this._SelectorNotUsingParam = value;
					this.SendPropertyChanged("SelectorNotUsingParam");
					this.OnSelectorNotUsingParamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelectorNotUsingBrowser", DbType="Bit NOT NULL")]
		public bool SelectorNotUsingBrowser
		{
			get
			{
				return this._SelectorNotUsingBrowser;
			}
			set
			{
				if ((this._SelectorNotUsingBrowser != value))
				{
					this.OnSelectorNotUsingBrowserChanging(value);
					this.SendPropertyChanging();
					this._SelectorNotUsingBrowser = value;
					this.SendPropertyChanged("SelectorNotUsingBrowser");
					this.OnSelectorNotUsingBrowserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelectorParamText", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string SelectorParamText
		{
			get
			{
				return this._SelectorParamText;
			}
			set
			{
				if ((this._SelectorParamText != value))
				{
					this.OnSelectorParamTextChanging(value);
					this.SendPropertyChanging();
					this._SelectorParamText = value;
					this.SendPropertyChanged("SelectorParamText");
					this.OnSelectorParamTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SqlViewStatePerPage", DbType="Bit NOT NULL")]
		public bool SqlViewStatePerPage
		{
			get
			{
				return this._SqlViewStatePerPage;
			}
			set
			{
				if ((this._SqlViewStatePerPage != value))
				{
					this.OnSqlViewStatePerPageChanging(value);
					this.SendPropertyChanging();
					this._SqlViewStatePerPage = value;
					this.SendPropertyChanged("SqlViewStatePerPage");
					this.OnSqlViewStatePerPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelectorNotUsingGeoIP", DbType="Bit NOT NULL")]
		public bool SelectorNotUsingGeoIP
		{
			get
			{
				return this._SelectorNotUsingGeoIP;
			}
			set
			{
				if ((this._SelectorNotUsingGeoIP != value))
				{
					this.OnSelectorNotUsingGeoIPChanging(value);
					this.SendPropertyChanging();
					this._SelectorNotUsingGeoIP = value;
					this.SendPropertyChanged("SelectorNotUsingGeoIP");
					this.OnSelectorNotUsingGeoIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelectorCookieName", DbType="NVarChar(30)")]
		public string SelectorCookieName
		{
			get
			{
				return this._SelectorCookieName;
			}
			set
			{
				if ((this._SelectorCookieName != value))
				{
					this.OnSelectorCookieNameChanging(value);
					this.SendPropertyChanging();
					this._SelectorCookieName = value;
					this.SendPropertyChanged("SelectorCookieName");
					this.OnSelectorCookieNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocaleDetectionOrder", DbType="NVarChar(20)")]
		public string LocaleDetectionOrder
		{
			get
			{
				return this._LocaleDetectionOrder;
			}
			set
			{
				if ((this._LocaleDetectionOrder != value))
				{
					this.OnLocaleDetectionOrderChanging(value);
					this.SendPropertyChanging();
					this._LocaleDetectionOrder = value;
					this.SendPropertyChanged("LocaleDetectionOrder");
					this.OnLocaleDetectionOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseWhiteSpaceRemover", DbType="Bit NOT NULL")]
		public bool UseWhiteSpaceRemover
		{
			get
			{
				return this._UseWhiteSpaceRemover;
			}
			set
			{
				if ((this._UseWhiteSpaceRemover != value))
				{
					this.OnUseWhiteSpaceRemoverChanging(value);
					this.SendPropertyChanging();
					this._UseWhiteSpaceRemover = value;
					this.SendPropertyChanged("UseWhiteSpaceRemover");
					this.OnUseWhiteSpaceRemoverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseLocaleTranslation", DbType="Bit NOT NULL")]
		public bool UseLocaleTranslation
		{
			get
			{
				return this._UseLocaleTranslation;
			}
			set
			{
				if ((this._UseLocaleTranslation != value))
				{
					this.OnUseLocaleTranslationChanging(value);
					this.SendPropertyChanging();
					this._UseLocaleTranslation = value;
					this.SendPropertyChanged("UseLocaleTranslation");
					this.OnUseLocaleTranslationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocaleTranslationRules", DbType="NVarChar(100)")]
		public string LocaleTranslationRules
		{
			get
			{
				return this._LocaleTranslationRules;
			}
			set
			{
				if ((this._LocaleTranslationRules != value))
				{
					this.OnLocaleTranslationRulesChanging(value);
					this.SendPropertyChanging();
					this._LocaleTranslationRules = value;
					this.SendPropertyChanged("LocaleTranslationRules");
					this.OnLocaleTranslationRulesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelectorParamAutoreplaceURL", DbType="Bit NOT NULL")]
		public bool SelectorParamAutoreplaceURL
		{
			get
			{
				return this._SelectorParamAutoreplaceURL;
			}
			set
			{
				if ((this._SelectorParamAutoreplaceURL != value))
				{
					this.OnSelectorParamAutoreplaceURLChanging(value);
					this.SendPropertyChanging();
					this._SelectorParamAutoreplaceURL = value;
					this.SendPropertyChanged("SelectorParamAutoreplaceURL");
					this.OnSelectorParamAutoreplaceURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelectorParamAutoreplaceSOLPART", DbType="Bit NOT NULL")]
		public bool SelectorParamAutoreplaceSOLPART
		{
			get
			{
				return this._SelectorParamAutoreplaceSOLPART;
			}
			set
			{
				if ((this._SelectorParamAutoreplaceSOLPART != value))
				{
					this.OnSelectorParamAutoreplaceSOLPARTChanging(value);
					this.SendPropertyChanging();
					this._SelectorParamAutoreplaceSOLPART = value;
					this.SendPropertyChanged("SelectorParamAutoreplaceSOLPART");
					this.OnSelectorParamAutoreplaceSOLPARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalAliasDefaults", DbType="NVarChar(400)")]
		public string PortalAliasDefaults
		{
			get
			{
				return this._PortalAliasDefaults;
			}
			set
			{
				if ((this._PortalAliasDefaults != value))
				{
					this.OnPortalAliasDefaultsChanging(value);
					this.SendPropertyChanging();
					this._PortalAliasDefaults = value;
					this.SendPropertyChanged("PortalAliasDefaults");
					this.OnPortalAliasDefaultsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNames", DbType="NVarChar(2000)")]
		public string CustomNames
		{
			get
			{
				return this._CustomNames;
			}
			set
			{
				if ((this._CustomNames != value))
				{
					this.OnCustomNamesChanging(value);
					this.SendPropertyChanging();
					this._CustomNames = value;
					this.SendPropertyChanged("CustomNames");
					this.OnCustomNamesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjustSqlSession", DbType="Bit")]
		public System.Nullable<bool> AdjustSqlSession
		{
			get
			{
				return this._AdjustSqlSession;
			}
			set
			{
				if ((this._AdjustSqlSession != value))
				{
					this.OnAdjustSqlSessionChanging(value);
					this.SendPropertyChanging();
					this._AdjustSqlSession = value;
					this.SendPropertyChanged("AdjustSqlSession");
					this.OnAdjustSqlSessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AntiSessionExpiration", DbType="Int")]
		public System.Nullable<int> AntiSessionExpiration
		{
			get
			{
				return this._AntiSessionExpiration;
			}
			set
			{
				if ((this._AntiSessionExpiration != value))
				{
					this.OnAntiSessionExpirationChanging(value);
					this.SendPropertyChanging();
					this._AntiSessionExpiration = value;
					this.SendPropertyChanged("AntiSessionExpiration");
					this.OnAntiSessionExpirationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AntiSessionExpirationTime", DbType="Int")]
		public System.Nullable<int> AntiSessionExpirationTime
		{
			get
			{
				return this._AntiSessionExpirationTime;
			}
			set
			{
				if ((this._AntiSessionExpirationTime != value))
				{
					this.OnAntiSessionExpirationTimeChanging(value);
					this.SendPropertyChanging();
					this._AntiSessionExpirationTime = value;
					this.SendPropertyChanged("AntiSessionExpirationTime");
					this.OnAntiSessionExpirationTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForceParamExistance", DbType="Bit NOT NULL")]
		public bool ForceParamExistance
		{
			get
			{
				return this._ForceParamExistance;
			}
			set
			{
				if ((this._ForceParamExistance != value))
				{
					this.OnForceParamExistanceChanging(value);
					this.SendPropertyChanging();
					this._ForceParamExistance = value;
					this.SendPropertyChanged("ForceParamExistance");
					this.OnForceParamExistanceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dnn1_Delisoft_TabLocalization_Portals")]
	public partial class dnn1_Delisoft_TabLocalization_Portal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PortalId;
		
		private string _LocaleKey;
		
		private string _PortalName;
		
		private string _LogoFile;
		
		private string _FooterText;
		
		private string _Description;
		
		private string _KeyWords;
		
		private string _BackgroundFile;
		
		private System.Nullable<int> _HomeTabId;
		
		private System.Nullable<int> _LoginTabId;
		
		private System.Nullable<int> _UserTabId;
		
		private System.Nullable<int> _SplashTabId;
		
		private string _DefaultPortalSkin;
		
		private string _DefaultPortalContainer;
		
		private string _DefaultAdminSkin;
		
		private string _DefaultAdminContainer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPortalIdChanging(int value);
    partial void OnPortalIdChanged();
    partial void OnLocaleKeyChanging(string value);
    partial void OnLocaleKeyChanged();
    partial void OnPortalNameChanging(string value);
    partial void OnPortalNameChanged();
    partial void OnLogoFileChanging(string value);
    partial void OnLogoFileChanged();
    partial void OnFooterTextChanging(string value);
    partial void OnFooterTextChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnKeyWordsChanging(string value);
    partial void OnKeyWordsChanged();
    partial void OnBackgroundFileChanging(string value);
    partial void OnBackgroundFileChanged();
    partial void OnHomeTabIdChanging(System.Nullable<int> value);
    partial void OnHomeTabIdChanged();
    partial void OnLoginTabIdChanging(System.Nullable<int> value);
    partial void OnLoginTabIdChanged();
    partial void OnUserTabIdChanging(System.Nullable<int> value);
    partial void OnUserTabIdChanged();
    partial void OnSplashTabIdChanging(System.Nullable<int> value);
    partial void OnSplashTabIdChanged();
    partial void OnDefaultPortalSkinChanging(string value);
    partial void OnDefaultPortalSkinChanged();
    partial void OnDefaultPortalContainerChanging(string value);
    partial void OnDefaultPortalContainerChanged();
    partial void OnDefaultAdminSkinChanging(string value);
    partial void OnDefaultAdminSkinChanged();
    partial void OnDefaultAdminContainerChanging(string value);
    partial void OnDefaultAdminContainerChanged();
    #endregion
		
		public dnn1_Delisoft_TabLocalization_Portal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PortalId
		{
			get
			{
				return this._PortalId;
			}
			set
			{
				if ((this._PortalId != value))
				{
					this.OnPortalIdChanging(value);
					this.SendPropertyChanging();
					this._PortalId = value;
					this.SendPropertyChanged("PortalId");
					this.OnPortalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocaleKey", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LocaleKey
		{
			get
			{
				return this._LocaleKey;
			}
			set
			{
				if ((this._LocaleKey != value))
				{
					this.OnLocaleKeyChanging(value);
					this.SendPropertyChanging();
					this._LocaleKey = value;
					this.SendPropertyChanged("LocaleKey");
					this.OnLocaleKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalName", DbType="NVarChar(128)")]
		public string PortalName
		{
			get
			{
				return this._PortalName;
			}
			set
			{
				if ((this._PortalName != value))
				{
					this.OnPortalNameChanging(value);
					this.SendPropertyChanging();
					this._PortalName = value;
					this.SendPropertyChanged("PortalName");
					this.OnPortalNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoFile", DbType="NVarChar(50)")]
		public string LogoFile
		{
			get
			{
				return this._LogoFile;
			}
			set
			{
				if ((this._LogoFile != value))
				{
					this.OnLogoFileChanging(value);
					this.SendPropertyChanging();
					this._LogoFile = value;
					this.SendPropertyChanged("LogoFile");
					this.OnLogoFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FooterText", DbType="NVarChar(100)")]
		public string FooterText
		{
			get
			{
				return this._FooterText;
			}
			set
			{
				if ((this._FooterText != value))
				{
					this.OnFooterTextChanging(value);
					this.SendPropertyChanging();
					this._FooterText = value;
					this.SendPropertyChanged("FooterText");
					this.OnFooterTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWords", DbType="NVarChar(500)")]
		public string KeyWords
		{
			get
			{
				return this._KeyWords;
			}
			set
			{
				if ((this._KeyWords != value))
				{
					this.OnKeyWordsChanging(value);
					this.SendPropertyChanging();
					this._KeyWords = value;
					this.SendPropertyChanged("KeyWords");
					this.OnKeyWordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackgroundFile", DbType="NVarChar(50)")]
		public string BackgroundFile
		{
			get
			{
				return this._BackgroundFile;
			}
			set
			{
				if ((this._BackgroundFile != value))
				{
					this.OnBackgroundFileChanging(value);
					this.SendPropertyChanging();
					this._BackgroundFile = value;
					this.SendPropertyChanged("BackgroundFile");
					this.OnBackgroundFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeTabId", DbType="Int")]
		public System.Nullable<int> HomeTabId
		{
			get
			{
				return this._HomeTabId;
			}
			set
			{
				if ((this._HomeTabId != value))
				{
					this.OnHomeTabIdChanging(value);
					this.SendPropertyChanging();
					this._HomeTabId = value;
					this.SendPropertyChanged("HomeTabId");
					this.OnHomeTabIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginTabId", DbType="Int")]
		public System.Nullable<int> LoginTabId
		{
			get
			{
				return this._LoginTabId;
			}
			set
			{
				if ((this._LoginTabId != value))
				{
					this.OnLoginTabIdChanging(value);
					this.SendPropertyChanging();
					this._LoginTabId = value;
					this.SendPropertyChanged("LoginTabId");
					this.OnLoginTabIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserTabId", DbType="Int")]
		public System.Nullable<int> UserTabId
		{
			get
			{
				return this._UserTabId;
			}
			set
			{
				if ((this._UserTabId != value))
				{
					this.OnUserTabIdChanging(value);
					this.SendPropertyChanging();
					this._UserTabId = value;
					this.SendPropertyChanged("UserTabId");
					this.OnUserTabIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SplashTabId", DbType="Int")]
		public System.Nullable<int> SplashTabId
		{
			get
			{
				return this._SplashTabId;
			}
			set
			{
				if ((this._SplashTabId != value))
				{
					this.OnSplashTabIdChanging(value);
					this.SendPropertyChanging();
					this._SplashTabId = value;
					this.SendPropertyChanged("SplashTabId");
					this.OnSplashTabIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultPortalSkin", DbType="NVarChar(200)")]
		public string DefaultPortalSkin
		{
			get
			{
				return this._DefaultPortalSkin;
			}
			set
			{
				if ((this._DefaultPortalSkin != value))
				{
					this.OnDefaultPortalSkinChanging(value);
					this.SendPropertyChanging();
					this._DefaultPortalSkin = value;
					this.SendPropertyChanged("DefaultPortalSkin");
					this.OnDefaultPortalSkinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultPortalContainer", DbType="NVarChar(200)")]
		public string DefaultPortalContainer
		{
			get
			{
				return this._DefaultPortalContainer;
			}
			set
			{
				if ((this._DefaultPortalContainer != value))
				{
					this.OnDefaultPortalContainerChanging(value);
					this.SendPropertyChanging();
					this._DefaultPortalContainer = value;
					this.SendPropertyChanged("DefaultPortalContainer");
					this.OnDefaultPortalContainerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultAdminSkin", DbType="NVarChar(200)")]
		public string DefaultAdminSkin
		{
			get
			{
				return this._DefaultAdminSkin;
			}
			set
			{
				if ((this._DefaultAdminSkin != value))
				{
					this.OnDefaultAdminSkinChanging(value);
					this.SendPropertyChanging();
					this._DefaultAdminSkin = value;
					this.SendPropertyChanged("DefaultAdminSkin");
					this.OnDefaultAdminSkinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultAdminContainer", DbType="NVarChar(200)")]
		public string DefaultAdminContainer
		{
			get
			{
				return this._DefaultAdminContainer;
			}
			set
			{
				if ((this._DefaultAdminContainer != value))
				{
					this.OnDefaultAdminContainerChanging(value);
					this.SendPropertyChanging();
					this._DefaultAdminContainer = value;
					this.SendPropertyChanged("DefaultAdminContainer");
					this.OnDefaultAdminContainerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dnn1_Delisoft_TabLocalization_Replacements")]
	public partial class dnn1_Delisoft_TabLocalization_Replacement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ReplacementId;
		
		private int _PortalId;
		
		private string _ReplacementName;
		
		private string _LanguagesIncluded;
		
		private string _TabsIncluded;
		
		private string _SearchFor;
		
		private string _ReplaceWith;
		
		private System.Nullable<int> _ReplacementOrder;
		
		private bool _Disabled;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReplacementIdChanging(int value);
    partial void OnReplacementIdChanged();
    partial void OnPortalIdChanging(int value);
    partial void OnPortalIdChanged();
    partial void OnReplacementNameChanging(string value);
    partial void OnReplacementNameChanged();
    partial void OnLanguagesIncludedChanging(string value);
    partial void OnLanguagesIncludedChanged();
    partial void OnTabsIncludedChanging(string value);
    partial void OnTabsIncludedChanged();
    partial void OnSearchForChanging(string value);
    partial void OnSearchForChanged();
    partial void OnReplaceWithChanging(string value);
    partial void OnReplaceWithChanged();
    partial void OnReplacementOrderChanging(System.Nullable<int> value);
    partial void OnReplacementOrderChanged();
    partial void OnDisabledChanging(bool value);
    partial void OnDisabledChanged();
    #endregion
		
		public dnn1_Delisoft_TabLocalization_Replacement()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplacementId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ReplacementId
		{
			get
			{
				return this._ReplacementId;
			}
			set
			{
				if ((this._ReplacementId != value))
				{
					this.OnReplacementIdChanging(value);
					this.SendPropertyChanging();
					this._ReplacementId = value;
					this.SendPropertyChanged("ReplacementId");
					this.OnReplacementIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalId", DbType="Int NOT NULL")]
		public int PortalId
		{
			get
			{
				return this._PortalId;
			}
			set
			{
				if ((this._PortalId != value))
				{
					this.OnPortalIdChanging(value);
					this.SendPropertyChanging();
					this._PortalId = value;
					this.SendPropertyChanged("PortalId");
					this.OnPortalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplacementName", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string ReplacementName
		{
			get
			{
				return this._ReplacementName;
			}
			set
			{
				if ((this._ReplacementName != value))
				{
					this.OnReplacementNameChanging(value);
					this.SendPropertyChanging();
					this._ReplacementName = value;
					this.SendPropertyChanged("ReplacementName");
					this.OnReplacementNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguagesIncluded", DbType="NVarChar(100)")]
		public string LanguagesIncluded
		{
			get
			{
				return this._LanguagesIncluded;
			}
			set
			{
				if ((this._LanguagesIncluded != value))
				{
					this.OnLanguagesIncludedChanging(value);
					this.SendPropertyChanging();
					this._LanguagesIncluded = value;
					this.SendPropertyChanged("LanguagesIncluded");
					this.OnLanguagesIncludedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TabsIncluded", DbType="NVarChar(100)")]
		public string TabsIncluded
		{
			get
			{
				return this._TabsIncluded;
			}
			set
			{
				if ((this._TabsIncluded != value))
				{
					this.OnTabsIncludedChanging(value);
					this.SendPropertyChanging();
					this._TabsIncluded = value;
					this.SendPropertyChanged("TabsIncluded");
					this.OnTabsIncludedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SearchFor", DbType="NVarChar(250)")]
		public string SearchFor
		{
			get
			{
				return this._SearchFor;
			}
			set
			{
				if ((this._SearchFor != value))
				{
					this.OnSearchForChanging(value);
					this.SendPropertyChanging();
					this._SearchFor = value;
					this.SendPropertyChanged("SearchFor");
					this.OnSearchForChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplaceWith", DbType="NVarChar(250)")]
		public string ReplaceWith
		{
			get
			{
				return this._ReplaceWith;
			}
			set
			{
				if ((this._ReplaceWith != value))
				{
					this.OnReplaceWithChanging(value);
					this.SendPropertyChanging();
					this._ReplaceWith = value;
					this.SendPropertyChanged("ReplaceWith");
					this.OnReplaceWithChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplacementOrder", DbType="Int")]
		public System.Nullable<int> ReplacementOrder
		{
			get
			{
				return this._ReplacementOrder;
			}
			set
			{
				if ((this._ReplacementOrder != value))
				{
					this.OnReplacementOrderChanging(value);
					this.SendPropertyChanging();
					this._ReplacementOrder = value;
					this.SendPropertyChanged("ReplacementOrder");
					this.OnReplacementOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disabled", DbType="Bit NOT NULL")]
		public bool Disabled
		{
			get
			{
				return this._Disabled;
			}
			set
			{
				if ((this._Disabled != value))
				{
					this.OnDisabledChanging(value);
					this.SendPropertyChanging();
					this._Disabled = value;
					this.SendPropertyChanged("Disabled");
					this.OnDisabledChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dnn1_Delisoft_TabLocalization_ViewState")]
	public partial class dnn1_Delisoft_TabLocalization_ViewState : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _vsKey;
		
		private string _vsValue;
		
		private System.DateTime _CreatedTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnvsKeyChanging(string value);
    partial void OnvsKeyChanged();
    partial void OnvsValueChanging(string value);
    partial void OnvsValueChanged();
    partial void OnCreatedTimeChanging(System.DateTime value);
    partial void OnCreatedTimeChanged();
    #endregion
		
		public dnn1_Delisoft_TabLocalization_ViewState()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vsKey", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string vsKey
		{
			get
			{
				return this._vsKey;
			}
			set
			{
				if ((this._vsKey != value))
				{
					this.OnvsKeyChanging(value);
					this.SendPropertyChanging();
					this._vsKey = value;
					this.SendPropertyChanged("vsKey");
					this.OnvsKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vsValue", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string vsValue
		{
			get
			{
				return this._vsValue;
			}
			set
			{
				if ((this._vsValue != value))
				{
					this.OnvsValueChanging(value);
					this.SendPropertyChanging();
					this._vsValue = value;
					this.SendPropertyChanged("vsValue");
					this.OnvsValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedTime", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedTime
		{
			get
			{
				return this._CreatedTime;
			}
			set
			{
				if ((this._CreatedTime != value))
				{
					this.OnCreatedTimeChanging(value);
					this.SendPropertyChanging();
					this._CreatedTime = value;
					this.SendPropertyChanged("CreatedTime");
					this.OnCreatedTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
