//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAS.DNNDataBase.DataBaseManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAS.DNNDataBase.DataBaseManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0815.ru
        ///0clickemail.com
        ///0-mail.com
        ///0wnd.net
        ///0wnd.org
        ///0x00.name
        ///10mail.org
        ///10minut.com.pl
        ///10minutemail.co.za
        ///10minutemail.com
        ///123-m.com
        ///14n.co.uk
        ///1-8.biz
        ///1fsdfdsfsdf.tk
        ///1pad.de
        ///1ss.noip.me
        ///20email.eu
        ///20mail.eu
        ///20mail.it
        ///20minute.email
        ///20minutemail.com
        ///2120001.net
        ///21cn.com
        ///2fdgdfgdfgdf.tk
        ///2prong.com
        ///30minutemail.com
        ///33mail.com
        ///3d-painting.com
        ///3l6.com
        ///3trtretgfrfe.tk
        ///4gfdsgfdgfd.tk
        ///4-n.us
        ///4w.io
        ///4warding.com
        ///4warding.net
        ///4warding.org
        ///5ghgfhfghfgh.tk
        ///5gramos.com
        ///5july.org
        ///6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BurnerEmailsProviders {
            get {
                return ResourceManager.GetString("BurnerEmailsProviders", resourceCulture);
            }
        }
    }
}
